plugins {
	id 'java'
}

repositories {
	mavenLocal()
	mavenCentral()
	maven { setUrl("https://maven.vaadin.com/vaadin-prereleases") }
	maven { setUrl("https://repo.spring.io/milestone") }
}

dependencies {
	implementation platform("com.vaadin:vaadin-bom:$vaadinVersion")
	implementation('com.vaadin:vaadin-core')
}
